name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Get Short Identifier
        uses: benjlevesque/short-sha@v2.2
        id: short-sha

      - name: Build
        id: build
        run: |
          chmod +x ./gradlew
          ./gradlew build
          rm -rf ./build/libs/*sources*
          VERSION_IDENTIFIER=SNAPSHOT+${{ steps.short-sha.outputs.sha }}
          FILE_NAME="$(ls ./build/libs -1 | head -n 1)"
          NEW_NAME="${FILE_NAME%.jar}-${VERSION_IDENTIFIER}.jar"
          mv "./build/libs/$FILE_NAME" "./build/libs/$NEW_NAME"
          echo "artifact_name=$NEW_NAME" >> "$GITHUB_OUTPUT"
          echo "artifact_path=./build/libs/$NEW_NAME" >> "$GITHUB_OUTPUT"

      - name: GitHub Action Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.artifact_name }}
          path: ${{ steps.build.outputs.artifact_path }}
